In [2]:
a,b,c = 1:3

1:3

In [3]:
t=1,x->x*x,"hola"

(1, var"#1#2"(), "hola")

In [7]:
t[1]
t[2]
t[3]

LoadError: UndefVarError: printil not defined

In [8]:
t[1:2]

(1, var"#1#2"())

In [9]:
# las listas son mutables pero las tuplas no

In [10]:
t="a","c","b",6,7,3,2
# acá no estámos re-definiendo la tupla anterior sino que ahora la variable t apunta a esta nueva tupla en memoria
# la tupla anterior sigue existiendo pero quedó "huerfana", eventualmente se borrará.

#ojo! tupla no es lo mismo que un "puntero" en C, sino que es algo más complejo

("a", "c", "b", 6, 7, 3, 2)

In [13]:
z=([1,"c",3],4)

(Any[1, "c", 3], 4)

In [14]:
z[1][2]="a"

"a"

In [15]:
z

(Any[1, "a", 3], 4)

In [16]:
#notemos que la tupla no es mutable pero si dentro tiene algo mutable se puede mutar

In [17]:
for i in (1,2,3,4,5,6)
    @show i
end

i = 1
i = 2
i = 3
i = 4
i = 5
i = 6


In [18]:
i=1
@macroexpand @show

quote
end

In [19]:
#Tuplas nombradas (numed tuples), es muy muy similar a "struct" de C

In [20]:
# fabriquemos un símbolo
:x

:x

In [24]:
#formalmente un arreglo se constuye así
x=Array{Any,1}(undef,a)

1-element Vector{Any}:
 #undef

In [27]:
N=2
M=3
k=5

zeros(N,M)
rand(N,M)
ones(N,M)
#crean matrices con ceros, numeros aleatorios y unos respectivamente

fill(k, N, M) #crea una matriz que tiene todos numeros k

2×3 Matrix{Int64}:
 5  5  5
 5  5  5

In [28]:
# Julia es row-major como FORTRAN pero recordar que C es colum-major

In [29]:
#al medir tiempos siempre hay que correr dos veces, porque la primera vez puede medir el tiempo de compilación

#medir tiempo con
@time

#o usen la alternativa
@btime

LoadError: LoadError: MethodError: no method matching var"@time"(::LineNumberNode, ::Module)
Closest candidates are:
  var"@time"(::LineNumberNode, ::Module, ::Any) at ~/julia-1.7.2/share/julia/base/timing.jl:214
in expression starting at In[29]:4

In [30]:
# no hay algo parecido a Switch case en Julia

In [31]:
?cat

search: cat catch catch_backtrace vcat hcat hvcat hvncat CartesianIndex



```
cat(A...; dims)
```

Concatenate the input arrays along the specified dimensions in the iterable `dims`. For dimensions not in `dims`, all input arrays should have the same size, which will also be the size of the output array along that dimension. For dimensions in `dims`, the size of the output array is the sum of the sizes of the input arrays along that dimension. If `dims` is a single number, the different arrays are tightly stacked along that dimension. If `dims` is an iterable containing several dimensions, this allows one to construct block diagonal matrices and their higher-dimensional analogues by simultaneously increasing several dimensions for every new input array and putting zero blocks elsewhere. For example, `cat(matrices...; dims=(1,2))` builds a block diagonal matrix, i.e. a block matrix with `matrices[1]`, `matrices[2]`, ... as diagonal blocks and matching zero blocks away from the diagonal.

See also [`hcat`](@ref), [`vcat`](@ref), [`hvcat`](@ref), [`repeat`](@ref).

# Examples

```jldoctest
julia> cat([1 2; 3 4], [pi, pi], fill(10, 2,3,1); dims=2)
2×6×1 Array{Float64, 3}:
[:, :, 1] =
 1.0  2.0  3.14159  10.0  10.0  10.0
 3.0  4.0  3.14159  10.0  10.0  10.0

julia> cat(true, trues(2,2), trues(4)', dims=(1,2))
4×7 Matrix{Bool}:
 1  0  0  0  0  0  0
 0  1  1  0  0  0  0
 0  1  1  0  0  0  0
 0  0  0  1  1  1  1
```


In [32]:
?view

search: view @view @views DivideError evalfile readavailable bytesavailable



```
view(A, inds...)
```

Like [`getindex`](@ref), but returns a lightweight array that lazily references (or is effectively a *view* into) the parent array `A` at the given index or indices `inds` instead of eagerly extracting elements or constructing a copied subset. Calling [`getindex`](@ref) or [`setindex!`](@ref) on the returned value (often a [`SubArray`](@ref)) computes the indices to access or modify the parent array on the fly.  The behavior is undefined if the shape of the parent array is changed after `view` is called because there is no bound check for the parent array; e.g., it may cause a segmentation fault.

Some immutable parent arrays (like ranges) may choose to simply recompute a new array in some circumstances instead of returning a `SubArray` if doing so is efficient and provides compatible semantics.

!!! compat "Julia 1.6"
    In Julia 1.6 or later, `view` can be called on an `AbstractString`, returning a `SubString`.


# Examples

```jldoctest
julia> A = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> b = view(A, :, 1)
2-element view(::Matrix{Int64}, :, 1) with eltype Int64:
 1
 3

julia> fill!(b, 0)
2-element view(::Matrix{Int64}, :, 1) with eltype Int64:
 0
 0

julia> A # Note A has changed even though we modified b
2×2 Matrix{Int64}:
 0  2
 0  4

julia> view(2:5, 2:3) # returns a range as type is immutable
3:4
```


In [33]:
#=

"r": Open for reading only, failing if no file exists
"r+": Open for reading and writing, failing if no file exists
"w"/"w+": Open for reading and writing, overwriting the file if it already exists
"a"/"a+": Open for reading and writing, creating a new file if none exists, but preserving the existing file if one is present

=#