In [5]:
1+1 # hola

2

In [2]:
using Pkg #hola

In [3]:
Pkg.add("Plots")

    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
  No Changes to `~/my_repositories/curso_julia_2022/my_new_project/Project.toml`
  No Changes to `~/my_repositories/curso_julia_2022/my_new_project/Manifest.toml`


In [4]:
using Plots

Esto es un Markdown

In [29]:
#=
escribo todo el
texto en 
distintos renglones
asi como re loquetoooo
=#

In [36]:
#Docstring
"""
aquí escribimos documentación

versión 0.001
hoy la escribi
"""

"aquí escribimos documentación\n\nversión 0.001\nhoy la escribi\n"

Clase03 - Operaciones Basicas
Introducción a la Programacion en Julia

In [9]:
println("Hello world Juliano!")
println("Excelente dia para aprender Julia")

Hello world Juliano!
Excelente dia para aprender Julia


In [10]:
print("Hello world Juliano!")
print("Excelente dia para aprender Julia")

Hello world Juliano!Excelente dia para aprender Julia

In [11]:
40+2

42

In [12]:
43-5

38

In [13]:
84/2

42.0

In [14]:
6^2+6

42

In [17]:
typeof("Hola,mundo")

String

In [16]:
typeof(2)

Int64

In [18]:
typeof(42.5)

Float64

In [19]:
mensaje="hola"

"hola"

In [20]:
typeof(mensaje)

String

In [21]:
n=15.6

15.6

In [22]:
typeof(n)

Float64

In [23]:
pi

π = 3.1415926535897...

In [24]:
typeof(pi)

Irrational{:π}

Un irrational es un valor "abstracto". Cuando Julia considera que es necesario convertirlo a flotante, lo hace.
solo que algunas funciones van a estar más optimizadas para trabajar con ciertos irracionales.
por ejemplo, sin(pi) va a ser mas rápido que sin(3.141592)
El compilador de julia intenta sacar ventaja de los irracionales

In [25]:
π

π = 3.1415926535897...

In [27]:
x=Float32(1.0)

1.0f0

In [28]:
typeof(x)

Float32

In [31]:
x=5
x+1

6

In [32]:
#Jupiter nos muestra la evaluación del último paso

In [34]:
println(x)

5


In [35]:
+(3,5)

#=
(los operadores en julia son funciones. Uno podría hacer una suma entre dos números a y b haciendo
+(a,b) )
=#

8

In [40]:
cadena="hola";

In [38]:
cadena +4

LoadError: MethodError: no method matching +(::String, ::Int64)
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at ~/julia-1.7.2/share/julia/base/operators.jl:655
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at ~/julia-1.7.2/share/julia/base/int.jl:87
  +(::Base.TwicePrecision, ::Number) at ~/julia-1.7.2/share/julia/base/twiceprecision.jl:279
  ...

In [39]:
cadenaxi=parse(Int64,cadena)

LoadError: ArgumentError: invalid base 10 digit 'h' in "hola"

In [44]:
vectorcito=["v11","v12","v13"]
vectoricito
println("vectorcito[1]")

LoadError: UndefVarError: vectoricito not defined

In [45]:
@doc print

```
print([io::IO], xs...)
```

Write to `io` (or to the default output stream [`stdout`](@ref) if `io` is not given) a canonical (un-decorated) text representation. The representation used by `print` includes minimal formatting and tries to avoid Julia-specific details.

`print` falls back to calling `show`, so most types should just define `show`. Define `print` if your type has a separate "plain" representation. For example, `show` displays strings with quotes, and `print` displays strings without quotes.

See also [`println`](@ref), [`string`](@ref), [`printstyled`](@ref).

# Examples

```jldoctest
julia> print("Hello World!")
Hello World!
julia> io = IOBuffer();

julia> print(io, "Hello", ' ', :World!)

julia> String(take!(io))
"Hello World!"
```


In [46]:
@doc sort

```
sort(v; alg::Algorithm=defalg(v), lt=isless, by=identity, rev::Bool=false, order::Ordering=Forward)
```

Variant of [`sort!`](@ref) that returns a sorted copy of `v` leaving `v` itself unmodified.

# Examples

```jldoctest
julia> v = [3, 1, 2];

julia> sort(v)
3-element Vector{Int64}:
 1
 2
 3

julia> v
3-element Vector{Int64}:
 3
 1
 2
```

```
sort(A; dims::Integer, alg::Algorithm=DEFAULT_UNSTABLE, lt=isless, by=identity, rev::Bool=false, order::Ordering=Forward)
```

Sort a multidimensional array `A` along the given dimension. See [`sort!`](@ref) for a description of possible keyword arguments.

To sort slices of an array, refer to [`sortslices`](@ref).

# Examples

```jldoctest
julia> A = [4 3; 1 2]
2×2 Matrix{Int64}:
 4  3
 1  2

julia> sort(A, dims = 1)
2×2 Matrix{Int64}:
 1  2
 4  3

julia> sort(A, dims = 2)
2×2 Matrix{Int64}:
 3  4
 1  2
```
